### ISSUE TITLE
testdata/testlines.tgz in 85-intro-ocroline  

### ISSUE THREAD

**Issue by ghost** [tmbdev-tutorials/das2018-tutorial#6]
Hi,  I have a question about testdata/testlines.tgz in 85-intro-ocroline

I unzip testlines.tgz and zipped again and do the same thing in the tutorial

It occures some error.

> missing keys, got ['__source__', 'txt', '__key__'], want {'image': 'png', 'transcript': 'txt'}

But the tgz file the you provided works well.

My question is..

Should I pre-process input data before training ocroline???

Sorry my bad english, Cause I'm not english speaker.

**Comment by bliu3650** [comment]
@a41888936 Example for your reference.
Extract it by
mkdir testlines
tar -xf testlines.tgz -C testlines
and create the achieve file by:
tar -cf testlines.tgz testlines/*   (note here it's a the file list, and index must be in order as author designed)

**Comment by ghost** [comment]
@BrianLiu3650 Thanks It works!
